### ISSUE TITLE
Enhancement needed  

### ISSUE THREAD

**Issue by michygeek** [Gear61/Random-Number-Generator#32]
Hello!!!
I have to say kodus for this sweet project here and i like to make a proposal on improving the project.
I and my folks have been using the app to play Ludo game and we have to use our mobile individually to play the game but lots of cheat used to happened because sometimes some guys will roll twice and we get to confused on the first roll that was originality made. That moved me to make this proposal

**Ability to connect mobile together using hotspot or bluetooth**

whereby users that decide to use the app to play game will have their device connected together and their will be name of the mobile showing within the app. So if Player A roll the dice it will show on others device that 4,6 is rolled by Player A and they will be forced to count as well as there won't be any means of cheat while playing and these will definitely be a very nice enhancement.
I know this might involve lots of coding and all that but at the long run it might end up being a win.

Thank you!!!

**Comment by Gear61** [comment]
I'm sorry; that is way out of scope for what this app does.

**Comment by yousifyou** [comment]
What is this game for?
