### ISSUE TITLE
Question about PRNG

### ISSUE THREAD

**Issue by ghost** [Gear61/Random-Number-Generator#35]
Hi
Does this project use a cryptographically secure PRNG?

**Comment by Gear61** [comment]
I have no idea, probably not. It's just the Random class built into Java.

**Comment by ghost** [comment]
It would be interesting to use more robust algorithms as a plus for the project,although not required. 
but we're looking for good quality random generator,in the end, randomness is the core of the project.
also add another sources of entropy could be interesting.

**Comment by Gear61** [comment]
@Da0012 If you know a clean, simple Java API that can do that without adding a lot more complexity to the project, I'm happy to hear.

**Comment by yousifyou** [comment]
How can I get benefit of this generator, and how can obtain the tojens

**Comment by Gear61** [comment]
@yousifyou Download the app...?

**Comment by Gear61** [comment]
@yousifyou Okay, you can now use the generator. Unsure what tokens you're referring to.

**Comment by yousifyou** [comment]
Yes I am!! Not sure.!

**Comment by elydpg** [comment]
java.util.Random is not cryptographically secure. You can use [java.security.SecureRandom](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) (which is a subclass of java.util.Random) for a cryptographically secure PRNG

**Comment by cauerego** [comment]
every year! 🤣

i wonder how i missed this back in #47
