### ISSUE TITLE
RNG min/max range is asymmetric

### ISSUE THREAD

**Issue by elydpg** [Gear61/Random-Number-Generator#42]
See this image

![asymmetric min/max range](https://i.imgur.com/6v5B507.jpg)

The least allowed negative integer is -99999999 (-10^8 + 1) while the greatest allowed positive integer 999999999 (10^9 - 1). In theory, the least allowed integer should be -10^9 + 1.

**Comment by Gear61** [comment]
This is intentional; it's capped by the limit of characters of the EditTexts.
