### ISSUE TITLE
More Dice Support

### ISSUE THREAD

**Issue by DonaldTsang** [Gear61/Random-Number-Generator#45]
Take a look at https://wiki.roll20.net/Dice_Reference and 
- JS https://github.com/GreenImp/rpg-dice-roller
- C++ https://github.com/Rolisteam/DiceParser
- Python https://github.com/the-nick-of-time/DnD
- C# https://github.com/skizzerz/DiceRoller
- PHP https://github.com/bakame-php/dice-roller

**Comment by Gear61** [comment]
I don't see anything actionable here; please refine it into a concrete use case if you want the issue to be potentially worked on.

**Comment by DonaldTsang** [comment]
@Gear61 concrete use case: Board games, especially Dungeons and Dragons
And the optimized play of board games requires https://github.com/Gear61/Random-Number-Generator/issues/48

**Comment by Gear61** [comment]
@DonaldTsang By concrete use case, I need a formal definition of input -> output and the UI/UX surrounding it as I unfortunately don't play D&D and I don't have time to convert a relatively rough definition to a fully working new feature. Feel free to submit a PR.

**Comment by DonaldTsang** [comment]
@Gear61 here are some of the basic features:
- arbitrary dice side counts (d4, d6, d8, d10, d12, d20, d100 being standard)
- Rolling multiple dice at one
- Being able to drop/keep the biggest or smallest numbers
- Being able to reroll certain numbered results
- Exploding/Compounding/Penetrating Dice
- Special Dice (e.g. fudge)
- Averages and Medians
Other features can be derived from these elements (excluding math operators)

For some good references (example designs):
- https://anydice.com/
- https://wiki.roll20.net/Dice_Reference
- https://github.com/Rolisteam/DiceParser/blob/master/HelpMe.md
- https://github.com/the-nick-of-time/DnD#rolling
- https://skizzerz.net/DiceRoller/Dice_Reference

I have made a checklist before https://github.com/GreenImp/rpg-dice-roller/issues/60
